# Generated by Django 5.0.2 on 2024-02-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product Description', max_length=20)),
                ('product_image', models.ImageField(null=True, upload_to='')),
            ],
            options={
                'ordering': ['-product_name', '-product_image'],
            },
        ),
    ]
