# Generated by Django 5.0.2 on 2024-02-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuritySolutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-product_name']},
        ),
    ]
