# Generated by Django 5.0.2 on 2024-03-17 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SecuritySolutions', '0002_alter_products_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['-product_name'], 'verbose_name_plural': 'Products'},
        ),
    ]
