# Generated by Django 5.0.2 on 2024-03-17 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SecuritySolutions', '0003_alter_products_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_description',
            field=models.CharField(help_text='Product Description', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(help_text='Product Name', max_length=20),
        ),
    ]
